### ISSUE TITLE
Support the notifications in the auto versioning configuration

### ISSUE THREAD

**Issue by dcoraboeuf** [nemerosa/ontrack-jenkins-cli-pipeline#32]
The AV configuration must support notifications. For example:

```yaml
dependencies:
  - ...
    notifications:
      - channel: mail
        config:
           # ...
        scope: ... # one of 
        notificationTemplate: ...
```

See https://github.com/nemerosa/ontrack/blob/master/ontrack-extension-auto-versioning/src/main/java/net/nemerosa/ontrack/extension/av/config/AutoVersioningNotification.kt for the complete structure.
